### ISSUE TITLE
feature: Float32 types

### ISSUE THREAD

**Issue by hubyhuby** [markbates/pop#205] opened 2018-02-18 09:48 UTC
Apparently the type float with the following syntax in buffalo generator works:
Long:Float lat:Float
Maybe it could be added as a ""Common" Types:" in the readme.

Float32 type seems to work but records wrong values : 
For example if we enter in the buffalo ressource generator: "long:nulls.Float32 lat:nulls.Float32"
An then If we type "0.1" it records when you edit "0.10000000149011612"
0.4321 gives 0.43209999799728394

**Comment by markbates** [comment] 2018-02-18 10:18
That’s the problem with floating point math. You would better using another data type that is precise. Floats aren’t precise.

**Comment by markbates** [comment] 2018-02-18 10:28
For more color on why floating point numbers are problematic in any language https://stackoverflow.com/questions/960072/rounding-errors

**Comment by markbates** [comment] 2018-02-18 10:29
I’m closing this since the problem is with floating points not necessarily pop. Please reopen if there’s something I’m missing.

**Comment by hubyhuby** [comment] 2018-02-18 10:29
Hi Mark,
Sorry if I seem a bit confusing, the reason is that I am learning buffalo and have a hard time knowing if I am facing bugs or not understanding some concepts....
Float works perfectly for me with the generator if I use the command "FLoat"
But when I first typed Float32 instead of Float I had the strange behaviour I described.

**Closed by markbates** 2018-02-18 10:29 UTC
